Turn api in rtc engine
membraneframework/stun pull request #1
Opened 2021-10-07 09:29 UTC by FelonEkonom

2021-11-02 16:27 UTC, FelonEkonom commented on src/turn.erl
> +         start_timestamp = get_timestamp() :: integer(), in_use :: boolean()}).
This change is due to the default formatting used by `rebar3`

2021-11-05 10:34 UTC, mickel8 requested changes

2021-11-05 10:34 UTC, mickel8 commented on src/turn.erl
> +maybe_send_to_ice_bin(#state{peer_pid = PeerPid}, Payload) ->
This lib shouldn't have dependency to ICE plugin. Could we rename this function somehow?

2021-11-08 10:11 UTC, mickel8 approved these changes

2021-11-08 11:03 UTC, merged